version: '3'

tasks:
  fetch-data:
    cmds:
      - python src/fetch_data.py
  embed:
    cmds:
      - python src/embed.py --model_name=Snowflake/snowflake-arctic-embed-m --n_components=64
  cluster:
    cmds:
      - python src/cluster.py
  name:
    cmds:
      - python src/name.py