version: '3'

tasks:
  fetch-data:
    cmds:
      - python src/fetch_data.py
  embed:
    cmds:
      - python src/embed.py --model_name=Snowflake/snowflake-arctic-embed-m --n_components=64
  cluster:
    cmds:
      - python src/cluster.py
  name:
    cmds:
      - python src/name.py
  evaluate:
    cmds:
      - python src/evaluate.py --embedding_model_name=Snowflake/snowflake-arctic-embed-m --distance_threshold=0.9
  visualize:
    cmds:
      - python src/visualize.py